/* Convolutional encoder and Viterbi decoder for K=7 rate=1/2 code
 * Copyright 1997 Phil Karn, KA9Q
 */

#include <string.h>

#include "viterbi27.h"
#include "vittab.h"

// int Rate = 2;

extern unsigned char Partab[];	/* Parity lookup table */

/* Convolutionally encode data into binary symbols */
int encode27(unsigned char *symbols,
	     unsigned char *data,
	     unsigned int nbytes
	     )
{
	unsigned char encstate;
	int i;

	encstate = 0;
	while(nbytes-- != 0){
		for(i=7;i>=0;i--){
			encstate = (encstate << 1) | ((*data >> i) & 1);
			*symbols++ = Partab[encstate & POLYA];
			*symbols++ = Partab[encstate & POLYB];
		}
		data++;
	}
	return 0;
}

/* Viterbi decoder */
int viterbi27(unsigned long *metric,	/* Final path metric (returned value) */
	      unsigned char *data,	/* Decoded output data */
	      unsigned char *symbols,	/* Raw deinterleaved input symbols */
	      unsigned int nbits	/* Number of output bits */
	      )
{
	unsigned int bitcnt = 0;
	int beststate,i;
	long cmetric[64],nmetric[64];
	/* This next line is arguably illegal C, but it works on
	 * GCC and it avoids having to reference this heavily used
	 * array through a pointer. If you can't compile this, use malloc.
	 */
	unsigned long paths[nbits*2*sizeof(unsigned long)];
	unsigned long *pp;
	register unsigned long dec;
	int mets[4];
	
	pp = paths;
	/* Initialize starting metrics to prefer 0 state */
	cmetric[0] = 0;
	for(i=1;i<64;i++)
		cmetric[i] = -999999;

	for(;;){
		/* Read input symbol pair and compute branch metrics */
		mets[0] = mettab[0][symbols[0]] + mettab[0][symbols[1]];
		mets[1] = mettab[0][symbols[0]] + mettab[1][symbols[1]];
		mets[3] = mettab[1][symbols[0]] + mettab[1][symbols[1]];
		mets[2] = mettab[1][symbols[0]] + mettab[0][symbols[1]];
		symbols += 2;

		/* These macro calls were generated by genbut.c
		 * and rearranged by hand for speed
		 */
		dec = 0;
		BUTTERFLY(0,0);
		BUTTERFLY(6,0);
		BUTTERFLY(8,0);
		BUTTERFLY(14,0);
		BUTTERFLY(2,3);
		BUTTERFLY(4,3);
		BUTTERFLY(10,3);
		BUTTERFLY(12,3);
		BUTTERFLY(1,1);
		BUTTERFLY(7,1);
		BUTTERFLY(9,1);
		BUTTERFLY(15,1);
		BUTTERFLY(3,2);
		BUTTERFLY(5,2);
		BUTTERFLY(11,2);
		BUTTERFLY(13,2);
		*pp++ = dec;
		dec = 0;
		BUTTERFLY(19,0);
		BUTTERFLY(21,0);
		BUTTERFLY(27,0);
		BUTTERFLY(29,0);
		BUTTERFLY(17,3);
		BUTTERFLY(23,3);
		BUTTERFLY(25,3);
		BUTTERFLY(31,3);
		BUTTERFLY(18,1);
		BUTTERFLY(20,1);
		BUTTERFLY(26,1);
		BUTTERFLY(28,1);
		BUTTERFLY(16,2);
		BUTTERFLY(22,2);
		BUTTERFLY(24,2);
		BUTTERFLY(30,2);
		*pp++ = dec;

		if(++bitcnt == nbits){
			beststate = 0;
			*metric = nmetric[beststate];
			break;
		}

		/* Read input symbol pair and compute branch metrics */
		mets[0] = mettab[0][symbols[0]] + mettab[0][symbols[1]];
		mets[1] = mettab[0][symbols[0]] + mettab[1][symbols[1]];
		mets[3] = mettab[1][symbols[0]] + mettab[1][symbols[1]];
		mets[2] = mettab[1][symbols[0]] + mettab[0][symbols[1]];
		symbols += 2;

		/* These macro calls were generated by genbut.c
		 * and rearranged by hand for speed
		 */
		dec = 0;
		BUTTERFLY2(0,0);
		BUTTERFLY2(6,0);
		BUTTERFLY2(8,0);
		BUTTERFLY2(14,0);
		BUTTERFLY2(2,3);
		BUTTERFLY2(4,3);
		BUTTERFLY2(10,3);
		BUTTERFLY2(12,3);
		BUTTERFLY2(1,1);
		BUTTERFLY2(7,1);
		BUTTERFLY2(9,1);
		BUTTERFLY2(15,1);
		BUTTERFLY2(3,2);
		BUTTERFLY2(5,2);
		BUTTERFLY2(11,2);
		BUTTERFLY2(13,2);
		*pp++ = dec;
		dec = 0;
		BUTTERFLY2(19,0);
		BUTTERFLY2(21,0);
		BUTTERFLY2(27,0);
		BUTTERFLY2(29,0);
		BUTTERFLY2(17,3);
		BUTTERFLY2(23,3);
		BUTTERFLY2(25,3);
		BUTTERFLY2(31,3);
		BUTTERFLY2(18,1);
		BUTTERFLY2(20,1);
		BUTTERFLY2(26,1);
		BUTTERFLY2(28,1);
		BUTTERFLY2(16,2);
		BUTTERFLY2(22,2);
		BUTTERFLY2(24,2);
		BUTTERFLY2(30,2);
		*pp++ = dec;

		if(++bitcnt == nbits){
			/* Or state with best metric, if no tail */
			beststate = 0;
			*metric = cmetric[beststate];
			break;
		}
	}
	pp -= 2;
	/* Chain back from terminal state to produce decoded data */
	memset(data,0,nbits/8);
	for(i=nbits-7;i >= 0;i--){
		if(pp[beststate >> 5] & (1 << (beststate & 31))){
			beststate |= 64;	/* 2^(K-1) */
			data[i>>3] |= 0x80 >> (i&7);
		}
		beststate >>= 1;
		pp -= 2;
	}
	return 0;
}
